# Generated by Django 4.2.7 on 2026-03-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrecord',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='status',
            field=models.CharField(choices=[('verified', 'Verified'), ('mismatch', 'Mismatch'), ('pending', 'Pending')], default='verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='expected_barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scanrecord',
            name='scanned_barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
