# Generated by Django 4.2.7 on 2026-03-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scanrecord_barcode_scanrecord_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='related_order',
        ),
    ]
