# Generated by Django 4.2.7 on 2026-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
